### ISSUE TITLE
[번역][영어]EC2 Systems Manager – Configure & Manage EC2 and On-Premises Systems

### ISSUE THREAD

**Issue by lsrock1** [awskrug/blog.awskr.org#10]
원문: 
[https://aws.amazon.com/ko/blogs/aws/ec2-systems-manager-configure-manage-ec2-and-on-premises-systems/](https://aws.amazon.com/ko/blogs/aws/ec2-systems-manager-configure-manage-ec2-and-on-premises-systems/)

**Comment by channy** [comment]
번역 감사드립니다. 이 글은 AWS 한국 블로그에 게시되었습니다. https://aws.amazon.com/ko/blogs/korea/ec2-systems-manager-configure-manage-ec2-and-on-premises-systems/
