### ISSUE TITLE
[번역요청][일본어] KMS로 인증정보를 암호화하고 Lambda실행시에 복호화 하기

### ISSUE THREAD

**Issue by serithemage** [awskrug/blog.awskr.org#2]
Lambda에서 KMS사용 예 입니다. classmethod측에는 허가 요청중입니다.
KMSで認証情報を暗号化しLambda実行時に復号化する
http://dev.classmethod.jp/cloud/decrypt-sensitive-data-with-kms-on-lambda-invocation/

**Comment by serithemage** [comment]
제가 가져가서 번역해 보겠습니다. 대략 목표 기간은 이번달 말 입니다.

**Comment by cloudnoa** [comment]
고객사에서 사용하는 사례와 같네요. ^^

**Comment by serithemage** [comment]
classmethod블로그의 모든 기사에 대해서 출처 표기를 전제로 번역 허가를 받았습니다.

**Comment by serithemage** [comment]
공개 완료!
http://www.awskr.org/2017/01/decrypt-sensitive-data-with-kms-on-lambda-invocation/
