### ISSUE TITLE
[번역요청][영어]Webpack과 자바스크립트용 AWS SDK 를 사용해 어플리케이션을 만들고 번들하기 - 파트 2

### ISSUE THREAD

**Issue by lsrock1** [awskrug/blog.awskr.org#8]
파트 2까지 마무리하겠습니다
[using-webpack-and-the-aws-sdk-for-javascript-to-create-and-bundle-an-application-part-2](https://aws.amazon.com/ko/blogs/developer/using-webpack-and-the-aws-sdk-for-javascript-to-create-and-bundle-an-application-part-2/)

**Comment by channy** [comment]
Two articles were published. Thanks for your effort!
